// examples/react-app/src/App.tsx
/**
 * Main App Component
 */

import { Routes, Route, Link, useLocation } from 'react-router-dom';
import { useUserContext } from '@error-explorer/react';
import { useRouterBreadcrumbs } from '@error-explorer/react/router';
import Home from './pages/Home';
import About from './pages/About';
import ErrorTest from './pages/ErrorTest';
import './App.css';

function App() {
  const location = useLocation();

  // Set user context for error tracking (id must be UUID or integer)
  useUserContext({
    id: '456',
    email: 'demo@react-example.com',
    name: 'React Demo User',
  });

  // Track navigation events
  useRouterBreadcrumbs(location, {
    trackNavigation: true,
    trackParams: false,
    trackQuery: false,
  });

  return (
    <div className="app">
      <header className="header">
        <h1>Error Explorer - React Example</h1>
        <nav>
          <Link to="/">Home</Link>
          <Link to="/about">About</Link>
          <Link to="/error-test">Error Test</Link>
        </nav>
      </header>

      <main className="main">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/about" element={<About />} />
          <Route path="/error-test" element={<ErrorTest />} />
        </Routes>
      </main>

      <footer className="footer">
        <p>React 18 + Error Explorer SDK Example</p>
      </footer>
    </div>
  );
}

export default App;

// examples/vue-app/src/App.vue
<script setup lang="ts">
import { useErrorExplorer, useUserContext } from '@error-explorer/vue';
import { onMounted } from 'vue';

const { setTag } = useErrorExplorer();

// Set user context for error tracking (id must be UUID or integer)
useUserContext({
  id: '123',
  email: 'demo@vue-example.com',
  name: 'Vue Demo User',
});

onMounted(() => {
  // Set app-wide tags
  setTag('app', 'vue-example');
  setTag('version', '1.0.0');
});
</script>

<template>
  <div class="app">
    <header class="header">
      <h1>Error Explorer - Vue Example</h1>
      <nav>
        <router-link to="/">Home</router-link>
        <router-link to="/about">About</router-link>
        <router-link to="/error-test">Error Test</router-link>
      </nav>
    </header>

    <main class="main">
      <router-view />
    </main>

    <footer class="footer">
      <p>Vue 3 + Error Explorer SDK Example</p>
    </footer>
  </div>
</template>

<style scoped>
.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.header {
  background: #42b883;
  color: white;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 20px;
}

.header h1 {
  margin-bottom: 10px;
  font-size: 24px;
}

.header nav {
  display: flex;
  gap: 15px;
}

.header nav a {
  color: white;
  text-decoration: none;
  padding: 5px 10px;
  border-radius: 4px;
  transition: background 0.2s;
}

.header nav a:hover,
.header nav a.router-link-active {
  background: rgba(255, 255, 255, 0.2);
}

.main {
  background: white;
  padding: 20px;
  border-radius: 8px;
  min-height: 400px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.footer {
  text-align: center;
  padding: 20px;
  color: #666;
  font-size: 14px;
}
</style>
